[package]
name = "api_hooking"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.52.0" 
features = [
    "Win32_Foundation", 
    "Win32_UI", 
    "Win32_UI_WindowsAndMessaging", 
    "Win32_System", 
    "Win32_System_LibraryLoader", 
    "Win32_System_Threading", 
    "Win32_System_Memory"
] 
