[package]
name = "execute_shellcode"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "17.0.1"
windows = { version = "0.52.0", features = ["Win32_System_LibraryLoader", "Win32_Foundation", "Win32_System_Memory", "Win32_System_Threading", "Win32_Security"] }
