[package]
name = "obf"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.79"
quote = "1.0.35"
rand = "0.8.5"
syn = { version = "2.0.55", features = ["full"] }
