[package]
name = "anti_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.30.5"
windows = { version = "0.52.0", features = ["Win32_System_SystemInformation", "Win32_Foundation", "Win32_System_Registry"] }
