[package]
name = "ixml"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58.0", features = ["Win32_Data_Xml_MsXml", "Win32_System_Com", "Win32_System_Diagnostics_Debug_ActiveScript", "implement"] }
windows-core = "0.58.0"
