[package]
name = "pe_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.52.0", features = ["Win32_System_SystemServices", "Win32_System_Diagnostics_Debug", "Win32_System_SystemInformation"] }
