[package]
name = "local_thread_hijacking"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.52.0"
features = [
    "Win32_System_Threading", 
    "Win32_Foundation", 
    "Win32_System_Diagnostics_Debug", 
    "Win32_System_Kernel", 
    "Win32_System_Diagnostics_ToolHelp", 
    "Win32_System_Memory"
]
