[package]
name = "shellcode_callback"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.52.0", features = ["Win32_System_Memory", "Win32_Globalization", "Win32_Foundation"] }
